package com.example.karunada_kala.model

import com.google.firebase.firestore.PropertyName

// ── Art Form ──────────────────────────────────────────────────────────────────
data class ArtForm(
    val id: String = "",
    val name: String = "",
    val region: String = "",
    val summary: String = "",
    val description: String = "",      // Auto-generated by Gemini if blank
    val imageUrl: String = "",
    val youtubeVideoId: String = "",
    
    @get:PropertyName("isAiGenerated")
    @set:PropertyName("isAiGenerated")
    var isAiGenerated: Boolean = false  // PRD §5.1: Shows 'Generated by AI' badge
)

// ── Artisan ───────────────────────────────────────────────────────────────────
data class Artisan(
    val id: String = "",
    val name: String = "",
    val email: String = "", // For admin reference and profile contact
    val artForms: List<String> = emptyList(),
    val district: String = "",
    val bio: String = "",
    val phone: String = "",
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val type: ArtisanType = ArtisanType.WORKSHOP,  // PRD §5.2: distinct map pin icons
    val imageUrl: String = "",
    val productImages: List<String> = emptyList()   // PRD §5.3: up to 6 product images
)

enum class ArtisanType { WORKSHOP, PERFORMANCE }

// ── Event ─────────────────────────────────────────────────────────────────────
data class KalaEvent(
    val id: String = "",
    val name: String = "",
    val artForm: String = "",
    val district: String = "",
    val dateTime: String = "",
    val imageUrl: String = "",
    val organiser: String = "",
    val organiserId: String = ""
)

// ── User ──────────────────────────────────────────────────────────────────────
enum class UserRole { EXPLORER, ARTISAN, ADMIN }

data class UserProfile(
    val uid: String = "",
    val name: String = "",
    val email: String = "",
    val phone: String = "", // Added phone number for all users
    val role: UserRole = UserRole.EXPLORER
)

// ── Workshop Registration ──────────────────────────────────────────────────────
/**
 * PRD §5.4: Saved to Firestore 'registrations' collection on Workshop Sign-Up.
 */
data class WorkshopRegistration(
    val id: String = "",
    val userId: String = "", // Added to track which user made the registration
    val fullName: String = "",
    val email: String = "",
    val phone: String = "",
    val artForm: String = "",
    val preferredDate: String = "",
    val message: String = "",
    val artisanName: String = "",
    val artisanId: String = "",
    val submittedAt: Long = System.currentTimeMillis()
)