package com.example.karunada_kala.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.karunada_kala.data.KalaViewModel
import com.example.karunada_kala.model.ArtForm
import com.example.karunada_kala.ui.components.KalaPrimaryButton
import com.example.karunada_kala.ui.components.KalaTopBar
import com.example.karunada_kala.ui.theme.Parchment

@Composable
fun AddArtFormScreen(onBackClick: () -> Unit, onSuccess: () -> Unit, viewModel: KalaViewModel = viewModel()) {
    var name by remember { mutableStateOf("") }
    var region by remember { mutableStateOf("") }
    var summary by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var imageUrl by remember { mutableStateOf("") }
    var videoId by remember { mutableStateOf("") }
    var isAiGenerated by remember { mutableStateOf(false) }
    var isSubmitting by remember { mutableStateOf(false) }

    Scaffold(topBar = { KalaTopBar("Add Art Form", showBack = true, onBackClick = onBackClick) }, containerColor = Parchment) { padding ->
        Column(modifier = Modifier.fillMaxSize().padding(padding).verticalScroll(rememberScrollState()).padding(20.dp)) {
            OutlinedTextField(value = name, onValueChange = { name = it }, label = { Text("Name") }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(value = region, onValueChange = { region = it }, label = { Text("Region") }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(value = summary, onValueChange = { summary = it }, label = { Text("Summary") }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(value = description, onValueChange = { description = it }, label = { Text("Description") }, modifier = Modifier.fillMaxWidth().height(120.dp), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(value = imageUrl, onValueChange = { imageUrl = it }, label = { Text("Image URL") }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(value = videoId, onValueChange = { videoId = it }, label = { Text("YouTube Video ID") }, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(10.dp), colors = kalaFieldColors())
            Spacer(Modifier.height(10.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(checked = isAiGenerated, onCheckedChange = { isAiGenerated = it })
                Text("Is AI Generated?")
            }
            Spacer(Modifier.height(28.dp))

            if (isSubmitting) {
                CircularProgressIndicator()
            } else {
                KalaPrimaryButton("Save Art Form") {
                    if (name.isNotBlank()) {
                        isSubmitting = true
                        val af = ArtForm(name = name, region = region, summary = summary, description = description, imageUrl = imageUrl, youtubeVideoId = videoId, isAiGenerated = isAiGenerated)
                        viewModel.addArtForm(af) {
                            isSubmitting = false
                            onSuccess()
                        }
                    }
                }
            }
        }
    }
}
